[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

#change esp32dev for seeed_xiao_esp32s3 or viceversa
#and add the build flags
#build_flags = 
#    -D ARDUINO_USB_MODE=1
#    -D ARDUINO_USB_CDC_ON_BOOT=1
#and delete them for esp32dev